package collection

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"regexp"
	"sort"
	"strings"
	"time"
)

var pathParamRE = regexp.MustCompile(`\{[a-zA-Z0-9_]+\+?\}`)

// ProbeExample is the result of one HTTP round-trip within a multi-round probe.
// All examples for a route are embedded as named responses in the Postman collection.
type ProbeExample struct {
	StatusCode     int               `json:"statusCode"`
	Body           string            `json:"body,omitempty"`
	Headers        map[string]string `json:"headers,omitempty"` // response headers
	DurationMs     int64             `json:"durationMs"`
	RequestHeaders map[string]string `json:"requestHeaders,omitempty"` // headers sent
	RequestBody    string            `json:"requestBody,omitempty"`    // body sent
	Label          string            `json:"label,omitempty"`          // probe label (schema-driven mode)
}

// ProbeRound is the aggregated result of all probe attempts for one gateway route.
// StatusCode/Body/Headers reflect the final (best) attempt.
// Examples contains every attempt for Postman embedding.
type ProbeRound struct {
	RouteKey   string            `json:"routeKey"`
	Method     string            `json:"method"`
	Path       string            `json:"path"`
	StatusCode int               `json:"statusCode,omitempty"`
	Headers    map[string]string `json:"headers,omitempty"`
	Body       string            `json:"body,omitempty"`
	DurationMs int64             `json:"durationMs"`
	Attempts   int               `json:"attempts,omitempty"`
	Error      string            `json:"error,omitempty"`
	Examples   []ProbeExample    `json:"examples,omitempty"`
	// NeedsInput is true when an enum validation error blocks further progress.
	// The probe pauses and waits for user-supplied values.
	NeedsInput  bool     `json:"needsInput,omitempty"`
	StuckFields []string `json:"stuckFields,omitempty"`
	// StuckOptions lists the known valid values for each stuck enum field.
	StuckOptions map[string][]string `json:"stuckOptions,omitempty"`
}

// RouteSpec is the minimal description of a route to probe.
type RouteSpec struct {
	RouteKey        string
	Method          string
	Path            string
	InvokeBase      string
	SeedBody        json.RawMessage
	RequiredHeaders map[string]string
	// FieldOverrides seeds the request body with user-supplied values before round 0.
	// Used when re-probing a stuck route — headers are also pre-seeded from RequiredHeaders.
	FieldOverrides map[string]interface{}
	// ProbeBodies, when non-empty, replaces the trial-and-error strategy with a
	// deterministic schema-driven probe sequence generated by probegen.GenerateProbes.
	ProbeBodies []ProbeBody
	// ExtractedPathId is a resource ID (UUID) extracted from a prior successful
	// POST response. When set, it replaces {param} placeholders in the path so
	// PATCH/GET/DELETE routes use the real created resource instead of "probe-id".
	ExtractedPathId string
}

const maxProbeRounds = 8

// commonFallbackHeaders is tried once when no header hints are extracted from a 4xx.
// These cover the most common auth patterns across Lambda-backed APIs.
var commonFallbackHeaders = []string{
	"Authorization",
	"x-api-key",
	"X-API-Key",
	"x-auth-token",
	"api-key",
}

// fallbackBodyBatches is tried in sequence for mutations when no body field hints
// are extracted. Each batch covers a common domain of required field names.
var fallbackBodyBatches = [][]string{
	{"id", "name", "type"},
	{"userId", "email", "status"},
	{"data", "payload", "body"},
	{"description", "items", "value"},
}

// methodPriority defines the execution order: POST creates resources first so
// downstream PATCH/GET routes can use the real resource ID.
var methodPriority = map[string]int{
	"POST": 0, "PUT": 1, "PATCH": 2, "DELETE": 3, "GET": 4,
}

// extractedIDRe matches a bare UUID anywhere in a response body.
var extractedIDRe = regexp.MustCompile(`[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`)

// RunProbes fires one multi-round probe per route spec and sends results to out.
// Routes are sorted POST-first so a created resource ID can be injected into
// the path parameters of subsequent PATCH/GET/DELETE routes.
func RunProbes(ctx context.Context, routes []RouteSpec, out chan<- ProbeRound) {
	client := &http.Client{Timeout: 10 * time.Second}

	// Sort a copy so POST runs before PATCH/GET/DELETE.
	sorted := make([]RouteSpec, len(routes))
	copy(sorted, routes)
	sort.SliceStable(sorted, func(i, j int) bool {
		pi := methodPriority[strings.ToUpper(sorted[i].Method)]
		pj := methodPriority[strings.ToUpper(sorted[j].Method)]
		if pi != pj {
			return pi < pj
		}
		return false
	})

	extractedID := "" // UUID from a successful POST, injected into later path params
	for _, r := range sorted {
		if ctx.Err() != nil {
			return
		}
		if extractedID != "" && r.ExtractedPathId == "" {
			r.ExtractedPathId = extractedID
		}
		result := multiProbe(ctx, client, r)
		// After a successful POST, extract a resource ID for downstream routes.
		if extractedID == "" && strings.ToUpper(normalizeMethod(r.Method)) == "POST" &&
			result.StatusCode >= 200 && result.StatusCode < 300 {
			if m := extractedIDRe.FindString(result.Body); m != "" {
				extractedID = m
			}
		}
		out <- result
	}
}

// multiProbe fires up to maxProbeRounds attempts for a route.
//
// Strategy per attempt after a 4xx:
//  1. Start bare (no custom headers) so round 0 always captures auth/header errors.
//  2. Extract header names from 4xx body → merge into headers.
//  3. Extract body field names + enum values → merge into body.
//  4. Fallback: merge declared RequiredHeaders (once), then common auth headers (once),
//     then cycle body-field batches until nothing new can be added.
//  5. If two consecutive rounds return identical status+body the probe is stuck.
//     The duplicate is discarded and the result is marked NeedsInput.
//
// When FieldOverrides is set (re-probe after user input) the declared RequiredHeaders
// are used as the starting headers (skipping bare-start header discovery) and the
// overrides are merged into the initial body.
func multiProbe(ctx context.Context, client *http.Client, r RouteSpec) ProbeRound {
	method := normalizeMethod(r.Method)

	// Schema-driven mode: use pre-generated probe bodies from zodparse/probegen.
	if len(r.ProbeBodies) > 0 {
		return schemaProbe(ctx, client, r, method)
	}

	isMutation := method == "POST" || method == "PUT" || method == "PATCH"

	isReprobe := len(r.FieldOverrides) > 0

	// Seed body.
	// Normal probe for mutations: start with nil (no body) so round 0 captures
	// "missing/malformed body" errors, then bootstrap to {}, then fill fields.
	// Re-probe: start with SeedBody + FieldOverrides already applied so we skip
	// the nil/empty bootstrap and jump straight to where we left off.
	var currentBody json.RawMessage
	if isReprobe {
		obj := make(map[string]interface{})
		if len(r.SeedBody) > 0 {
			_ = json.Unmarshal(r.SeedBody, &obj)
		}
		for k, v := range r.FieldOverrides {
			obj[k] = v
		}
		if data, err := json.Marshal(obj); err == nil {
			currentBody = data
		}
	} else if isMutation {
		currentBody = nil // nil → no body → bootstrap
	} else {
		currentBody = r.SeedBody
	}

	// Seed headers.
	// Normal probe: start bare so round 0 captures auth/header 400s.
	// Re-probe: start with RequiredHeaders — user already saw header errors.
	var currentHeaders map[string]string
	knownHeadersDone := false
	if isReprobe {
		currentHeaders = copyStringMap(r.RequiredHeaders)
		knownHeadersDone = true
	} else {
		currentHeaders = map[string]string{}
	}

	var examples []ProbeExample
	var last ProbeRound

	// Track previous response to detect stuck loops.
	prevStatus := -1
	prevBody := "\x00" // sentinel — can't match a real response on first attempt

	// Fallback state — tracked across attempts so each fallback is applied at most once.
	fallbackHeadersDone := false
	fallbackBodyIdx := 0

	for attempt := 0; attempt < maxProbeRounds; attempt++ {
		// Capture the effective request BEFORE probing so it can be shown in the UI.
		reqHeaders := effectiveHeaders(currentHeaders)
		reqBody := string(currentBody)

		last = singleProbe(ctx, client, r, method, currentBody, currentHeaders)

		// Stuck detection: same status + body as previous round → no progress possible.
		// Discard the duplicate and signal the frontend to ask the user for a value.
		if last.StatusCode == prevStatus && last.Body == prevBody {
			stuckFields := extractFieldHints(last.Body)
			return ProbeRound{
				RouteKey:    r.RouteKey,
				Method:      r.Method,
				Path:        r.Path,
				StatusCode:  last.StatusCode,
				Headers:     last.Headers,
				Body:        last.Body,
				DurationMs:  last.DurationMs,
				Attempts:    len(examples),
				Examples:    examples,
				NeedsInput:  true,
				StuckFields: stuckFields,
			}
		}
		prevStatus = last.StatusCode
		prevBody = last.Body

		examples = append(examples, ProbeExample{
			StatusCode:     last.StatusCode,
			Body:           last.Body,
			Headers:        last.Headers,
			DurationMs:     last.DurationMs,
			RequestHeaders: reqHeaders,
			RequestBody:    reqBody,
		})

		if last.Error != "" || last.StatusCode == 0 {
			break // network failure
		}
		if last.StatusCode >= 200 && last.StatusCode < 300 {
			break // success
		}
		if last.StatusCode >= 500 {
			break // server error — retrying won't help
		}

		// --- primary: extract hints from the 4xx response body ---
		newHeaders := mergeStringMapsUpdating(currentHeaders, extractHeaderHints(last.Body))
		var newBody = currentBody
		if isMutation {
			if currentBody == nil {
				// Bootstrap step 1: upgrade nil → empty object to trigger field validation.
				newBody = json.RawMessage(`{}`)
			} else {
				fieldHints := extractFieldHints(last.Body)
				enumOptions := extractEnumHints(last.Body) // map[field][]validValues

				// Check for enum fields that are blocking progress.
				// If a field is already in the body with a non-enum probe value AND
				// the response reports an enum error for it, we can't auto-fill —
				// pause and ask the user for the correct value.
				if len(enumOptions) > 0 {
					var stuck []string
					obj := make(map[string]interface{})
					_ = json.Unmarshal(currentBody, &obj)
					for field := range enumOptions {
						cur, exists := obj[field]
						// Field is blocking if it's missing OR set to a generic probe value
						if !exists || cur == "probe-value" || cur == "" {
							stuck = append(stuck, field)
						}
					}
					if len(stuck) > 0 {
						// Filter stuckOptions to only the fields we're stuck on
						stuckOpts := make(map[string][]string, len(stuck))
						for _, f := range stuck {
							stuckOpts[f] = enumOptions[f]
						}
						return ProbeRound{
							RouteKey:     r.RouteKey,
							Method:       r.Method,
							Path:         r.Path,
							StatusCode:   last.StatusCode,
							Headers:      last.Headers,
							Body:         last.Body,
							DurationMs:   last.DurationMs,
							Attempts:     len(examples),
							Examples:     examples,
							NeedsInput:   true,
							StuckFields:  stuck,
							StuckOptions: stuckOpts,
						}
					}
				}

				// No enum blockage — build improved body with field hints only.
				newBody = buildImprovedBody(currentBody, fieldHints, nil)
			}
		}

		headersChanged := !mapsEqual(newHeaders, currentHeaders)
		bodyChanged := !bytes.Equal(newBody, currentBody)

		// --- fallback: merge declared RequiredHeaders (once) ---
		if !headersChanged && !knownHeadersDone && len(r.RequiredHeaders) > 0 {
			newHeaders = mergeStringMapsUpdating(newHeaders, r.RequiredHeaders)
			knownHeadersDone = true
			headersChanged = !mapsEqual(newHeaders, currentHeaders)
		}

		// --- fallback: add common auth headers (once) when no hints extracted ---
		if !headersChanged && !fallbackHeadersDone {
			for _, h := range commonFallbackHeaders {
				if _, exists := newHeaders[h]; !exists {
					newHeaders[h] = "probe-value"
				}
			}
			fallbackHeadersDone = true
			headersChanged = !mapsEqual(newHeaders, currentHeaders)
		}

		// --- fallback: cycle through body field batches for mutations ---
		if isMutation && !bodyChanged && fallbackBodyIdx < len(fallbackBodyBatches) {
			candidate := buildImprovedBody(newBody, fallbackBodyBatches[fallbackBodyIdx], nil)
			fallbackBodyIdx++
			if !bytes.Equal(candidate, newBody) {
				newBody = candidate
				bodyChanged = true
			}
		}

		if !headersChanged && !bodyChanged {
			break // nothing new to try
		}

		currentHeaders = newHeaders
		currentBody = newBody
	}

	return ProbeRound{
		RouteKey:   r.RouteKey,
		Method:     r.Method,
		Path:       r.Path,
		StatusCode: last.StatusCode,
		Headers:    last.Headers,
		Body:       last.Body,
		DurationMs: last.DurationMs,
		Error:      last.Error,
		Attempts:   len(examples),
		Examples:   examples,
	}
}

// effectiveHeaders returns a copy of headers with "" values replaced by "probe-value",
// matching exactly what singleProbe will send over the wire.
func effectiveHeaders(h map[string]string) map[string]string {
	out := make(map[string]string, len(h))
	for k, v := range h {
		if v == "" {
			v = "probe-value"
		}
		out[k] = v
	}
	return out
}

func normalizeMethod(m string) string {
	m = strings.ToUpper(m)
	if m == "ANY" || m == "$DEFAULT" || m == "" {
		return "GET"
	}
	return m
}

func singleProbe(ctx context.Context, client *http.Client, r RouteSpec, method string, seedBody json.RawMessage, headers map[string]string) ProbeRound {
	round := ProbeRound{RouteKey: r.RouteKey, Method: r.Method, Path: r.Path}

	pathID := "probe-id"
	if r.ExtractedPathId != "" {
		pathID = r.ExtractedPathId
	}
	path := pathParamRE.ReplaceAllString(r.Path, pathID)
	url := strings.TrimRight(r.InvokeBase, "/") + path

	isMutation := method == "POST" || method == "PUT" || method == "PATCH"
	var bodyReader io.Reader
	if isMutation && len(seedBody) > 0 {
		bodyReader = bytes.NewReader(seedBody)
	}

	req, err := http.NewRequestWithContext(ctx, method, url, bodyReader)
	if err != nil {
		round.Error = err.Error()
		return round
	}
	if isMutation && len(seedBody) > 0 {
		req.Header.Set("Content-Type", "application/json")
	}
	for k, v := range headers {
		if v == "" {
			v = "probe-value" // never send an empty header value
		}
		req.Header.Set(k, v)
	}

	start := time.Now()
	resp, err := client.Do(req)
	round.DurationMs = time.Since(start).Milliseconds()
	if err != nil {
		round.Error = err.Error()
		return round
	}
	defer resp.Body.Close()

	round.StatusCode = resp.StatusCode
	round.Headers = make(map[string]string, len(resp.Header))
	for k := range resp.Header {
		round.Headers[k] = resp.Header.Get(k)
	}
	data, _ := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	round.Body = string(data)
	return round
}

// ── Header hint extraction ────────────────────────────────────────────────────

// awsParamListRE matches AWS API Gateway's "missing request parameters" format:
// {"message": "Missing required request parameters: [method.request.header.x-api-key, ...]"}
var awsParamListRE = regexp.MustCompile(`(?i)Missing required request parameters[:\s]*\[([^\]]+)\]`)

// headerHintPatterns matches common prose/framework patterns that name a missing header.
var headerHintPatterns = []*regexp.Regexp{
	// "missing header: x-api-key" / "missing required header x-api-key"
	regexp.MustCompile(`(?i)missing\s+(?:required\s+)?headers?[:\s]+([a-zA-Z][a-zA-Z0-9-]+)`),
	// "x-api-key header is required/missing"
	regexp.MustCompile(`(?i)([a-zA-Z][a-zA-Z0-9-]+)\s+header\s+(?:is\s+)?(?:required|missing)`),
	// "Header 'x-api-key' is required"
	regexp.MustCompile(`(?i)header\s+'?([a-zA-Z][a-zA-Z0-9-]+)'?\s+(?:is\s+)?(?:required|missing)`),
	// "required header: x-api-key"
	regexp.MustCompile(`(?i)required\s+headers?[:\s]+([a-zA-Z][a-zA-Z0-9-]+)`),
	// "x-api-key is required" / "x-auth-token is missing" — hyphenated header names
	regexp.MustCompile(`(?i)\b(x-[a-zA-Z][a-zA-Z0-9-]+)\s+(?:is\s+)?(?:required|missing)\b`),
	// "Authorization is required" / "Bearer is required" — well-known auth header names
	regexp.MustCompile(`(?i)\b(authorization|bearer|x-api-key|x-auth-token|api-key|x-access-token)\s+(?:header\s+)?(?:is\s+)?(?:required|missing)\b`),
}

// extractHeaderHints returns a map of header-name → "probe-value" for every
// header name found in the 4xx response body.
func extractHeaderHints(responseBody string) map[string]string {
	result := make(map[string]string)

	// AWS API Gateway bulk list: [method.request.header.x-api-key, ...]
	if m := awsParamListRE.FindStringSubmatch(responseBody); len(m) > 1 {
		for _, raw := range strings.Split(m[1], ",") {
			raw = strings.TrimSpace(raw)
			// Strip "method.request.header." / "method.request.querystring." prefixes
			raw = strings.TrimPrefix(raw, "method.request.header.")
			raw = strings.TrimPrefix(raw, "method.request.querystring.")
			if raw != "" && !strings.ContainsAny(raw, " {}()") {
				result[raw] = "probe-value"
			}
		}
	}

	for _, re := range headerHintPatterns {
		for _, m := range re.FindAllStringSubmatch(responseBody, -1) {
			if len(m) > 1 {
				name := strings.TrimSpace(m[1])
				if name != "" && !strings.ContainsAny(name, " {}()") {
					result[name] = "probe-value"
				}
			}
		}
	}

	return result
}

// ── Body field hint extraction ────────────────────────────────────────────────

// fieldHintPatterns covers common validation framework error message formats.
// Each pattern must capture the field name in group 1.
var fieldHintPatterns = []*regexp.Regexp{
	// Joi:   "fieldName" is required
	regexp.MustCompile(`"([a-zA-Z_][a-zA-Z0-9_.]*)" is required`),
	// JSON Schema / AJV:  must have required property 'fieldName'
	regexp.MustCompile(`must have required property '([a-zA-Z_][a-zA-Z0-9_]*)'`),
	// AJV path prefix:  data/fieldName must be
	regexp.MustCompile(`data/([a-zA-Z_][a-zA-Z0-9_]*) must be`),
	// Generic prose:  missing (required) field: fieldName
	regexp.MustCompile(`(?i)missing\s+(?:required\s+)?fields?[:\s]+([a-zA-Z_][a-zA-Z0-9_]*)`),
	// fieldName is required  (no quotes)
	regexp.MustCompile(`\b([a-zA-Z_][a-zA-Z0-9_]*) is required\b`),
	// fieldName: required
	regexp.MustCompile(`\b([a-zA-Z_][a-zA-Z0-9_]*):\s*(?:")?required(?:")?`),
}

// extractFieldHints parses a 4xx response body and returns field names that
// appear to be missing or required. Covers Joi, Zod, AJV, Express Validator,
// and generic prose patterns.
func extractFieldHints(responseBody string) []string {
	seen := make(map[string]struct{})
	var fields []string
	add := func(name string) {
		name = strings.TrimSpace(name)
		if name == "" || len(name) > 64 || strings.ContainsAny(name, " /-\\()") {
			return
		}
		if _, ok := seen[name]; !ok {
			seen[name] = struct{}{}
			fields = append(fields, name)
		}
	}

	// Strategy 1: JSON structure analysis (Zod, Express Validator, nested objects)
	var doc interface{}
	if json.Unmarshal([]byte(responseBody), &doc) == nil {
		walkForFieldHints(doc, add)
	}

	// Strategy 2: regex on raw body text
	for _, re := range fieldHintPatterns {
		for _, m := range re.FindAllStringSubmatch(responseBody, -1) {
			if len(m) > 1 {
				add(m[1])
			}
		}
	}

	return fields
}

// isValidationMessage returns true when a string looks like a "this field is required"
// validation message. Covers a wide range of framework styles.
func isValidationMessage(msg string) bool {
	lower := strings.ToLower(msg)
	for _, kw := range []string{
		"required", "must not be null", "cannot be null", "must not be empty",
		"cannot be empty", "not null", "is missing", "is required", "must be provided",
		"cannot be blank", "must not be blank",
	} {
		if strings.Contains(lower, kw) {
			return true
		}
	}
	return false
}

// walkForFieldHints recursively inspects parsed JSON for common validation
// error structures and calls add() for each discovered field name.
func walkForFieldHints(v interface{}, add func(string)) {
	switch val := v.(type) {
	case map[string]interface{}:
		// Custom/modified-Zod: {"fieldErrors": [{"field": "batchStatus", "message": "must not be null"}]}
		if errs, ok := val["fieldErrors"]; ok {
			if arr, ok2 := errs.([]interface{}); ok2 {
				for _, item := range arr {
					if obj, ok3 := item.(map[string]interface{}); ok3 {
						if field, ok4 := obj["field"].(string); ok4 && field != "" {
							add(field) // always add — any fieldErrors entry needs value
						}
					}
				}
				return
			}
		}

		// Zod: {"path": ["fieldName"], "message": "Required"}
		if path, ok := val["path"]; ok {
			if msg, _ := val["message"].(string); isValidationMessage(msg) {
				switch p := path.(type) {
				case []interface{}:
					if len(p) > 0 {
						if s, ok2 := p[0].(string); ok2 {
							add(s)
						}
					}
				case string:
					add(p)
				}
			}
		}

		// Express Validator: {"path": "fieldName", "msg": "..."}
		if pathStr, ok := val["path"].(string); ok {
			if _, hasMsg := val["msg"]; hasMsg {
				add(pathStr)
			}
		}

		// {"errors": {"fieldName": "is required"}}
		if errs, ok := val["errors"]; ok {
			if errMap, ok2 := errs.(map[string]interface{}); ok2 {
				for k, ev := range errMap {
					if msg, ok3 := ev.(string); ok3 {
						if isValidationMessage(msg) {
							add(k)
						}
					} else {
						walkForFieldHints(ev, add)
					}
				}
				return // handled, don't fall through to generic key scan
			}
			walkForFieldHints(errs, add)
		}

		// Generic: any key whose string value mentions a validation keyword is probably a field name
		for k, v2 := range val {
			switch k {
			case "message", "error", "msg", "errors", "path", "code", "status", "statusCode", "stack":
				walkForFieldHints(v2, add)
			default:
				if s, ok2 := v2.(string); ok2 {
					if isValidationMessage(s) {
						add(k)
					}
				} else {
					walkForFieldHints(v2, add)
				}
			}
		}

	case []interface{}:
		for _, item := range val {
			walkForFieldHints(item, add)
		}
	}
}

// ── Enum hint extraction ──────────────────────────────────────────────────────

// enumHintREs matches patterns that declare a field's allowed enum values.
// Group 1 = field name, Group 2 = values list (comma/pipe/space separated).
var enumHintREs = []*regexp.Regexp{
	// Joi: "status" must be one of [PENDING, ACTIVE, INACTIVE]
	regexp.MustCompile(`"([a-zA-Z_][a-zA-Z0-9_.]*)" must be one of \[([^\]]+)\]`),
	// Generic: status must be one of [A, B] or status must be one of: A, B
	regexp.MustCompile(`\b([a-zA-Z_][a-zA-Z0-9_]*) must be one of[:\s\[]+([^\]"}{]+)`),
	// Zod prose: "type" must be 'CREATE' | 'UPDATE' | 'DELETE'
	regexp.MustCompile(`"([a-zA-Z_][a-zA-Z0-9_.]*)" must be ('(?:[^']+)'(?:\s*\|\s*'(?:[^']+)')+)`),
	// "Invalid value for 'status'. Allowed: PENDING | ACTIVE"
	regexp.MustCompile(`(?i)(?:invalid|not\s+(?:a\s+valid|one\s+of)).*?'?([a-zA-Z_][a-zA-Z0-9_]*)'?.*?(?:allowed|expected|valid)[:\s]+([A-Z][A-Z0-9_\s|,'"]+)`),
	// "status is not one of the allowed values: PENDING, ACTIVE"
	regexp.MustCompile(`\b([a-zA-Z_][a-zA-Z0-9_]*) is not one of.*?(?:values?|options?)[:\s]+([A-Z][A-Z0-9_\s,|'"]+)`),
}

// extractEnumHints returns a map of field → all valid enum values found in the 4xx body.
// Used to detect enum-blocked fields and present options to the user.
func extractEnumHints(responseBody string) map[string][]string {
	result := make(map[string][]string)

	// JSON parse for structured enum errors (Zod, modified Zod, etc.)
	var doc interface{}
	if json.Unmarshal([]byte(responseBody), &doc) == nil {
		walkForEnumHints(doc, result)
	}

	// Regex on raw body text
	for _, re := range enumHintREs {
		for _, m := range re.FindAllStringSubmatch(responseBody, -1) {
			if len(m) < 3 {
				continue
			}
			field := strings.TrimSpace(m[1])
			if field == "" {
				continue
			}
			vals := splitEnumValues(m[2])
			if len(vals) > 0 {
				if _, exists := result[field]; !exists {
					result[field] = vals
				}
			}
		}
	}
	return result
}

// enumInMessageRE extracts allowed values from messages like:
// "must be one of: PENDING, ACTIVE" or "allowed values are: A | B"
var enumInMessageRE = regexp.MustCompile(`(?i)(?:must be one of|allowed(?:\s+values?)?(?:\s+are)?)[:\s\[]+([A-Za-z0-9_,\s|'"]+)`)

// walkForEnumHints handles structured enum errors from multiple formats:
//   - Zod: {"code": "invalid_enum_value", "options": ["PENDING", "ACTIVE"], "path": ["status"]}
//   - Custom: {"fieldErrors": [{"field": "batchStatus", "message": "must be one of: PENDING, ACTIVE"}]}
func walkForEnumHints(v interface{}, result map[string][]string) {
	switch val := v.(type) {
	case map[string]interface{}:
		// Zod structured enum error — collects all options
		if code, _ := val["code"].(string); code == "invalid_enum_value" {
			path, _ := val["path"].([]interface{})
			opts, _ := val["options"].([]interface{})
			if len(path) > 0 && len(opts) > 0 {
				if field, ok := path[0].(string); ok && field != "" {
					if _, exists := result[field]; !exists {
						var options []string
						for _, o := range opts {
							if s, ok2 := o.(string); ok2 && s != "" {
								options = append(options, s)
							}
						}
						if len(options) > 0 {
							result[field] = options
						}
					}
				}
			}
		}

		// Custom/modified-Zod: {"fieldErrors": [{"field": "batchStatus", "message": "must be one of: PENDING, ACTIVE"}]}
		if errs, ok := val["fieldErrors"]; ok {
			if arr, ok2 := errs.([]interface{}); ok2 {
				for _, item := range arr {
					if obj, ok3 := item.(map[string]interface{}); ok3 {
						field, _ := obj["field"].(string)
						msg, _ := obj["message"].(string)
						if field != "" && msg != "" {
							if m := enumInMessageRE.FindStringSubmatch(msg); len(m) > 1 {
								vals := splitEnumValues(m[1])
								if len(vals) > 0 {
									if _, exists := result[field]; !exists {
										result[field] = vals
									}
								}
							}
						}
					}
				}
			}
		}

		for _, v2 := range val {
			walkForEnumHints(v2, result)
		}
	case []interface{}:
		for _, item := range val {
			walkForEnumHints(item, result)
		}
	}
}

// splitEnumValues splits a raw enum options string on commas, pipes, or spaces
// and strips surrounding quotes and brackets.
func splitEnumValues(s string) []string {
	s = strings.Trim(s, "[]\"' \t\n")
	parts := regexp.MustCompile(`[\s,|]+`).Split(s, -1)
	var vals []string
	for _, p := range parts {
		v := strings.Trim(strings.TrimSpace(p), `'"`)
		if v != "" && !strings.ContainsAny(v, " (){}") {
			vals = append(vals, v)
		}
	}
	return vals
}

// ── Body construction ─────────────────────────────────────────────────────────

// smartProbeValue returns a type-aware placeholder for a field based on naming conventions.
func smartProbeValue(name string) interface{} {
	lower := strings.ToLower(name)
	switch {
	case strings.HasSuffix(lower, "timestamp") || strings.HasSuffix(lower, "time") ||
		strings.HasSuffix(lower, "date") || strings.HasSuffix(lower, "at") ||
		strings.HasSuffix(lower, "datetime"):
		return "2024-01-01T00:00:00.000Z"
	case strings.HasSuffix(lower, "email"):
		return "probe@example.com"
	case lower == "id" || strings.HasSuffix(lower, "id") || strings.HasSuffix(lower, "uuid"):
		return "00000000-0000-0000-0000-000000000001"
	case strings.HasSuffix(lower, "count") || strings.HasSuffix(lower, "size") ||
		strings.HasSuffix(lower, "limit") || strings.HasSuffix(lower, "offset") ||
		strings.HasSuffix(lower, "amount") || strings.HasSuffix(lower, "number"):
		return 1
	case strings.HasSuffix(lower, "enabled") || strings.HasSuffix(lower, "active") ||
		strings.HasSuffix(lower, "flag"):
		return true
	default:
		return "probe-value"
	}
}

// buildImprovedBody merges field names and enum-specific values into an existing
// JSON object body.
//   - fieldNames: added with smartProbeValue() if not already present.
//   - enumHints: added with their specific value; also upgrades existing "probe-value"
//     placeholders so enum validation passes on the next round.
func buildImprovedBody(existing json.RawMessage, fieldNames []string, enumHints map[string]string) json.RawMessage {
	if len(fieldNames) == 0 && len(enumHints) == 0 {
		return existing
	}
	obj := make(map[string]interface{})
	if len(existing) > 0 {
		_ = json.Unmarshal(existing, &obj)
	}
	changed := false

	// Apply enum-specific values first; upgrade "probe-value" placeholders.
	for k, v := range enumHints {
		if cur, exists := obj[k]; !exists || cur == "probe-value" {
			obj[k] = v
			changed = true
		}
	}
	// Apply generic required-field hints with smart type-aware placeholders.
	for _, name := range fieldNames {
		cur, exists := obj[name]
		if !exists {
			obj[name] = smartProbeValue(name)
			changed = true
		} else if cur == "probe-value" {
			// Upgrade "probe-value" to a smarter placeholder if we can
			if smart := smartProbeValue(name); smart != "probe-value" {
				obj[name] = smart
				changed = true
			}
		}
	}
	if !changed {
		return existing
	}
	data, err := json.Marshal(obj)
	if err != nil {
		return existing
	}
	return data
}

// ── Map helpers ───────────────────────────────────────────────────────────────

func copyStringMap(m map[string]string) map[string]string {
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

// mergeStringMaps returns a new map combining base and additions.
// Keys already present in base are not overwritten.
func mergeStringMaps(base, additions map[string]string) map[string]string {
	if len(additions) == 0 {
		return base
	}
	merged := copyStringMap(base)
	for k, v := range additions {
		if _, exists := merged[k]; !exists {
			merged[k] = v
		}
	}
	return merged
}

// mergeStringMapsUpdating is like mergeStringMaps but also overwrites existing keys
// whose current value is an empty string. This lets hint extraction upgrade a
// pre-declared header placeholder ("") to an actionable value ("probe-value"),
// which makes mapsEqual correctly detect that something changed.
func mergeStringMapsUpdating(base, additions map[string]string) map[string]string {
	if len(additions) == 0 {
		return base
	}
	merged := copyStringMap(base)
	for k, v := range additions {
		if existing, exists := merged[k]; !exists || existing == "" {
			merged[k] = v
		}
	}
	return merged
}

func mapsEqual(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if b[k] != v {
			return false
		}
	}
	return true
}

// ── Schema-driven probing ─────────────────────────────────────────────────────

// schemaProbe executes each ProbeBody in sequence, collecting results as examples.
// Each body is fired exactly once — no retry/discovery loops.
func schemaProbe(ctx context.Context, client *http.Client, r RouteSpec, method string) ProbeRound {
	var examples []ProbeExample
	var last ProbeRound

	for _, pb := range r.ProbeBodies {
		if ctx.Err() != nil {
			break
		}

		// Merge route-level RequiredHeaders with body-specific headers.
		headers := mergeStringMaps(r.RequiredHeaders, pb.Headers)

		var body json.RawMessage
		if pb.Malformed {
			// Send intentionally broken JSON (one extra closing brace).
			body = json.RawMessage(`{}}`)
		} else {
			body = pb.Body
		}

		reqHeaders := effectiveHeaders(headers)
		reqBody := string(body)

		last = singleProbe(ctx, client, r, method, body, headers)

		ex := ProbeExample{
			StatusCode:     last.StatusCode,
			Body:           last.Body,
			Headers:        last.Headers,
			DurationMs:     last.DurationMs,
			RequestHeaders: reqHeaders,
			RequestBody:    reqBody,
			Label:          pb.Label,
		}
		examples = append(examples, ex)

		if last.Error != "" || last.StatusCode == 0 || last.StatusCode >= 500 {
			break // network / server failure — stop
		}
	}

	return ProbeRound{
		RouteKey:   r.RouteKey,
		Method:     r.Method,
		Path:       r.Path,
		StatusCode: last.StatusCode,
		Headers:    last.Headers,
		Body:       last.Body,
		DurationMs: last.DurationMs,
		Error:      last.Error,
		Attempts:   len(examples),
		Examples:   examples,
	}
}
